spring:
  datasource:
    url: jdbc:mysql://rm-6wexg0y7u6x16c1x255620.mysql.japan.rds.aliyuncs.com:3306/cartisan?characterEncoding=utf-8&useSSL=false
    username: cartisan
    password: 123@qazwsx
  jpa:
    show-sql: true

  rabbitmq:
    host: 47.245.58.216
    port: 5672
    virtual-host: /cartisan
    username: rabbitmqadmin
    password: 123456

  redis:
    host: 47.245.58.216 # Redis服务器地址
    database: 0 # Redis数据库索引（默认为0）
    port: 6379 # Redis服务器连接端口
    password: # Redis服务器连接密码（默认为空）
    jedis:
      pool:
        max-active: 8 # 连接池最大连接数（使用负值表示没有限制）
        max-wait: -1ms # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 8 # 连接池中的最大空闲连接
        min-idle: 0 # 连接池中的最小空闲连接
    timeout: 200ms # 连接超时时间（毫秒）

  zipkin:
    base-url: http://47.245.58.216:9411   # 指定zipkin的服务端的地址

  sleuth:
    sampler:
      probability: 1.0 # 将采样比例设置为 1.0，也就是全部都需要。默认是 0.1

cartisan:
  signature:
    enable: false
    secret: cartisan
