spring:
  rabbitmq:
    host: 49.234.49.112
    port: 5672
    virtual-host: /cartisan
    username: rabbitmqadmin
    password: 123456

  redis:
    host: 49.234.49.112
    port: 6379

#zuul:
#  routes:
#    base:
#      path: /swagger-proxy/base/**
#      serviceId: base
#    management:
#      path: /swagger-proxy/management/**
#      serviceId: management
#    myProduct:
#      path: /myProduct/**
#      serviceId: cartisan-example-product
#      # 敏感头的过滤，不会传到后端去，默认是 3 个【Cookie,Set-Cookie,Authorization】，设成空表示不过滤，需要传到后端去
#      sensitiveHeaders:
#  # 全部服务忽略敏感头
#  sensitiveHeaders:

management:
  endpoints:
    web:
      exposure:
        include: "*"

ribbon:
  ReadTimeout: 60000  # 单位毫秒数
  SocketTimeout: 60000

